### PR TITLE
remove .nolocal (remnant from prebuild)

### PR DESCRIPTION
**Pull request by ralphtheninja**
See discussion in https://github.com/prebuild/prebuild-install/pull/80

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I'd like to release this and #78 and put it into leveldown before releasing _that_.

**Comment by ralphtheninja** [comment]
`.nolocal` doesn't seem to be used anywhere (`depgrep nolocal prebuild-install` gives no output) but since we're removing functionality it should be a new major.

**Comment by mathiask88** [comment]
I'm on mobile, but LGTM

**Comment by ralphtheninja** [comment]
4.0.0

**Pull request merged**
