### PR TITLE
document cache

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by mathiask88** [comment]
What about documenting the `nolocal` option together with these changes?

**Comment by ralphtheninja** [comment]
> What about documenting the nolocal option together with these changes?

I had completely forgotten about that. It seems to have originated from `prebuild`. @mathiask88 Do you remember the story behind it?

**Comment by ralphtheninja** [comment]
Aaah here we go. https://github.com/prebuild/prebuild/commit/72a161a00a40eacb0215efec85b768ea535015a1

**Comment by ralphtheninja** [comment]
I think it was incorrectly documented here https://github.com/prebuild/prebuild/commit/ce6358c2fcab01ed5473464834c244a5c9a42c71#diff-04c6e90faac2675aa89e2176d2eec7d8R190 .. since `.nolocal == true` would still check cached prebuilds, but not locally cached prebuilds.

I'm wondering why it was added in the first place.

**Comment by ralphtheninja** [comment]
@mathiask88 I'm thinking we could remove `nolocal` since no one seems to use it anyway. We would have to release a new major again though.

**Comment by mathiask88** [comment]
Yes you are right. Does the local cache check makes any sense for `prebuild-install?` Maybe we can remove that and move the `nolocal`?

**Comment by ralphtheninja** [comment]
@brett19 Mind helping us shed some light into this? :smile:

**Comment by ralphtheninja** [comment]
> Yes you are right. Does the local cache check makes any sense for prebuild-install? Maybe we can remove that and move the nolocal?

I'm thinking the same, that it might not make sense anymore.

**Comment by ralphtheninja** [comment]
@mathiask88 I think I'll update the `nolocal` stuff in a separate PR.

**Pull request merged**
