### PR TITLE
Pass through download argument from npm

### LINKED ISSUE #43: Environmental variable options not passed through npm
I am working on a [wrapper for npm](https://viewer.scuttlebot.io/%25IdZKhhIsSEw4i3MFLRmkBfvIUHujkGlAl7pwWbigQVQ%3D.sha256) where I want to be able to run npm with either a command-line flag or environmental variable to tell `prebuild-install` to download prebuilds from a URL other than GitHub. I see that `prebuild-install` uses `rc` and a `download` config option to set the download URL. Setting the environmental variable `prebuild-install_download` to my custom URL template works when running `prebuild-install` from the command-line - however, it does not work when it is run via an `npm` script (`npm run install`). From some debugging, I found that `npm` seems to not pass through env vars with a hyphen, and since `prebuild-install`s `rc` prefix has a hyphen, none of its env vars get passed through. Setting `download=...` in `~/.prebuild-installrc` works, but I would prefer not to touch the file system.

Would a PR be welcomed here that added a way to pass through the `download` option from `npm`'s cli args or env vars, in a non-breaking way? I am thinking the simplest way would be to use an env var without a hypen, like `prebuildinstall_download`, as a default for the `download` config option in `rc.js`. Or is there a better alternative that I am missing?

### PR DESCRIPTION
**Pull request by clehner**
Fix #43 using solution proposed in https://github.com/prebuild/prebuild-install/issues/43#issuecomment-333261243

cc @ralphtheninja

### CODE REVIEW

**Comment by ralphtheninja** [comment]
LGTM

**Comment by ralphtheninja** [comment]
It would be nice with one more review so we can get this out to @clehner

**Comment by juliangruber** [comment]
Can we add some documentation for this? To me it's not obvious from just looking at the diff.

**Comment by clehner** [comment]
@juliangruber I've added a note in the readme documenting how the options can be passed through via npm arguments. Is that good? The `--download` option itself is already in the readme/usage.

**Comment by ralphtheninja** [comment]
2.3.0

**Comment by clehner** [comment]
Thanks!

**Pull request merged**
