### PR TITLE
bump to latest node-abi (Node 12/Electron 5)

### PR DESCRIPTION
**Pull request by shiftkey**
https://github.com/lgeiger/node-abi/pull/62 adds support for detecting Electron 5 and Node 12

### CODE REVIEW

**Comment by vweevers** [comment]
Is this change (and https://github.com/prebuild/prebuild/pull/248) intended to prevent npm dedupe?

**Comment by shiftkey** [comment]
If this is only needed in one of the projects, feel free to close the other. I wasn't aware that it wasn't unnecessary to update both here...

**Comment by vweevers** [comment]
Both use `^2` so the `node-abi` update should float in automatically, unless you have some other module that depends on `node-abi` with a more restrictive semver range?

**Comment by shiftkey** [comment]
@vweevers let me test out a PR on a downstream project and see if I encounter an issue 🤘

**Comment by shiftkey** [comment]
Looks like these PRs are unnecessary: https://github.com/atom/node-keytar/pull/181

Thanks for the extra insight @vweevers and apologies for the noise!

**Comment by vweevers** [comment]
No worries! Glad it works out.

**Pull request closed without merging**
