### PR TITLE
Add --force flag to force the use of prebuilt binaries when available

### LINKED ISSUE #47: How do you force prebuild-install to NOT compile from source/ALWAYS download prebuild binaries?
Really, I'd just like to force prebuild-install to NEVER skip the prebuilt option (they exist for a reason, after all!)

### PR DESCRIPTION
**Pull request by ian-axiadids**
Resolves #47.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@ian-axiadids Mind doing `git commit --amend` and force push to trigger travis?

**Comment by ian-axiadids** [comment]
@ralphtheninja The Travis CI build passed, whenever you're ready.

**Comment by ralphtheninja** [comment]
Anyone against this change? I'm +1.

**Comment by ralphtheninja** [comment]
2.4.0

**Pull request merged**
