### PR TITLE
Drop node 0.x support

### PR DESCRIPTION
**Pull request by mathiask88**
This PR:
- use const
- use arrow functions
- replace fs.exists with fs.access
- use Object.assign() instead of `xtend`
- upgrades dependencies that already dropped support

I don't like supporting node versions that are not longer maintained. 

Your opinions @mafintosh @ralphtheninja @juliangruber @lgeiger ?

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I'm +-0 on this. I personally have the same opinion to throw out the old and in with the new :) At the same time it's also nice to be backwards compatible so for that reason this should be a new major.

**Comment by mathiask88** [comment]
The main reason was that we start getting stuck on old dependencies just to support old stuff.

**Comment by lgeiger** [comment]
👍 For dropping Node 0.x support and moving things forward.

We should also mention the supported Node versions in the readme and `package.json`: https://docs.npmjs.com/files/package.json#engines

**Comment by mathiask88** [comment]
> We should also mention the supported Node versions in the readme and package.json: https://docs.npmjs.com/files/package.json#engines

Yes, but this is advisory only (except strict mode). Maybe it would be a good idea if `prebuild-install` would exit gracefully if the ABI version is lower than e.g. 46. Then it is still possible for an addon to get compiled.

**Comment by lgeiger** [comment]
> Yes, but this is advisory only (except strict mode).

You're right, I overlooked it.

> Maybe it would be a good idea if prebuild-install would exit gracefully if the ABI version is lower than e.g. 46. Then it is still possible for an addon to get compiled.

That's a good idea 👍

**Comment by mafintosh** [comment]
👎 on code changes to the repo just to use new features. it works fine as is.
👍 to not include super old versions in the default --all build list

**Comment by mafintosh** [comment]
i guess the --all comment is mostly relevant to prebuild so i'm just 👎 on the code changes.

**Pull request closed without merging**
