### PR TITLE
add osx to travis

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Seems osx builds are not working well on travis, https://travis-ci.org/prebuild/prebuild-install/builds/332716077

They never start. I've seen this on builds for `leveldown` as well.

**Comment by mathiask88** [comment]
They had an issue with their OSX images. They need some time to start but they do https://travis-ci.org/mathiask88/node-snap7/builds/331010179

**Comment by ralphtheninja** [comment]
From Jan 19th https://www.traviscistatus.com/incidents/mc9x2wmpnvhg

**Comment by ralphtheninja** [comment]
I'm going to merge this for now. And will make sure to run the tests before we release next version. Hopefully it will not take too long for travis to fix the osx issues.

**Pull request merged**
