### PR TITLE
Move to GitHub Actions

### PR DESCRIPTION
**Pull request by vweevers**

### CODE REVIEW

**Comment by vweevers** [comment]
> Workflow runs completed with no jobs

Hmz.

**Comment by vweevers** [comment]
Can someone spot a mistake? The workflow is not starting.

**Comment by mafintosh** [comment]
@vweevers i'd imagine they don't run it until it's merged due to security reasons.

**Comment by vweevers** [comment]
The workflows on https://github.com/prebuild/node-gyp-build/pull/39 and https://github.com/prebuild/prebuildify/pull/51 did start. AFAICT the circumstances are the same.

I'll merge and we'll see.

**Comment by vweevers** [comment]
Actions were enabled/allowed in both https://github.com/organizations/prebuild/settings/actions and https://github.com/prebuild/prebuild-install/settings/actions, yet the workflow didn't start on master either. Then I checked https://github.com/prebuild/prebuild-install/actions and it showed a button to enable Actions, so I clicked that. Finally, the workflow started.

However, the audit log shows that @zeke enabled Actions 🤷‍♂️ 

image

**Comment by zeke** [comment]
Hi there! Not sure I had anything to do with this. 🤷🏼 

Cool to see this happening though. 👍🏼

**Pull request merged**
