### PR TITLE
Inline no longer maintained `noop-logger`

### LINKED ISSUE #154: Consider inlining `noop-logger`
Hi, we are shipping your node module with VS Code, so I wanted to start by thanking you for your work!

According to https://github.com/segmentio/noop-logger/issues/2 , the `noop-logger` repository is no longer maintained and the recommendation is to simply inline the code where needed. 

The background is that we end up also shipping `noop-logger` with VS Code and are having trouble figuring out how to attribute the npm module correctly (i.e. the license is missing a Copyright statement, which is an integral part of the MIT license -- https://opensource.org/licenses/MIT).

### PR DESCRIPTION
**Pull request by alexdima**
Fixes #154

### CODE REVIEW

**Review by mathiask88 — APPROVED** [review]

**Review by ralphtheninja — APPROVED** [review]

**Review by vweevers — APPROVED** [review]

**Comment by vweevers** [comment]
@ralphtheninja Got time and energy to make a release? I don't 😃

**Comment by ralphtheninja** [comment]
> @ralphtheninja Got time and energy to make a release? I don't 😃

Yeah, I can do that.

**Comment by ralphtheninja** [comment]
https://github.com/prebuild/prebuild-install/releases/tag/v6.1.3

**Comment by alexdima** [comment]
Thank you! 🎉

**Pull request merged**
